version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productservice
    volumes:
      - product-inventory-system-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/productservice
      DB_USERNAME: root
      DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/productservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  product-inventory-system-db-data: